These are Matt Langston's developer notes to himself. This file will
go away in the future for I want to keep it around during the
development of the HAL library.

* Travis CI
As of 2014.09.20 Travis CI only supports Xcode 5.1 which lacks support
for measureBlock.

* JSString
  JSString::operator std::string() const HAL_NOEXCEPT {
    HAL_JSSTRING_LOCK_GUARD;
    static std::wstring_convert<std::codecvt_utf8_utf16<char16_t>,char16_t> converter;
    auto self = const_cast<JSString*>(this);
    std::call_once(self -> string_once_flag__, [self]() {
      self -> string__ = std::string(converter.to_bytes(static_cast<std::u16string>(*self)));
    });
    return string__;
  }
  
  JSString::operator std::u16string() const HAL_NOEXCEPT {
    HAL_JSSTRING_LOCK_GUARD;
    auto self = const_cast<JSString*>(this);
    std::call_once(self -> u16string_once_flag__, [self]() {
      const JSChar* string_ptr = JSStringGetCharactersPtr(self -> js_string_ref__);
      self -> u16string__ = std::u16string(string_ptr, string_ptr + self -> length());
    });
    return u16string__;
  }
  
  std::size_t JSString::hash_value() const {
    HAL_JSSTRING_LOCK_GUARD;
    auto self = const_cast<JSString*>(this);
    std::call_once(self -> hash_value_once_flag__, [self]() {
      std::hash<std::string> hash_function = std::hash<std::string>();
      self -> hash_value__ = hash_function(static_cast<std::string>(*self));
    });
    return hash_value__;
  }

* JSExportObject.hpp
    /*!
     @method
     
     @abstract Return a property of this JavaScript object by numeric
     index. This method is equivalent to calling GetProperty with a
     string containing the numeric index, but provides optimized
     access for numeric properties.
     
     @param property_index An integer value that is the property's
     name.
     
     @result The property's value if this JavaScript object has the
     property, otherwise JSUndefined.
     */
    virtual JSValue GetProperty2(unsigned property_index) const HAL_NOEXCEPT final;
    
    
    /*!
     @method
     
     @abstract Set a property on this JavaScript object with an
     optional set of attributes.
     
     @param property_name The name of the property to set.
     
     @param value The value of the the property to set.
     
     @param attributes An optional set of property attributes to give
     to the property.
     
     @result true if the the property was set.
     */
    virtual bool SetProperty2(const JSString& property_name, const JSValue& property_value, const std::unordered_set<JSPropertyAttribute>& attributes) HAL_NOEXCEPT final;
    
    /*!
     @method
     
     @abstract Set a property on this JavaScript object by numeric
     index. This method is equivalent to calling SetProperty with a
     string containing the numeric index, but provides optimized
     access for numeric properties.
     
     @param property_index An integer value that is the property's
     name.
     
     @param value The value of the the property to set.
     
     @result true if the the property was set.
     */
    virtual bool SetProperty3(unsigned property_index, const JSValue& property_value) HAL_NOEXCEPT final;

* JSExportObject.cpp
  JSValue JSExportObject::GetProperty2(unsigned property_index) const HAL_NOEXCEPT {
    return js_object__.GetProperty(property_index);
  }
  
  bool JSExportObject::SetProperty2(const JSString& property_name, const JSValue& property_value, const std::unordered_set<JSPropertyAttribute>& attributes) HAL_NOEXCEPT {
    HAL_JSEXPORTOBJECT_LOCK_GUARD;
    
    // TODO: Provide the virtual function
    //
    // virtual bool WillSetProperty(property_name, property_value);
    //
    // that derived classes can implement for property validation and
    // custom access control (e.g. to enforce security policies)."
    
    if (js_object__.HasProperty(property_name)) {
      JSValue previous_value = js_object__.GetProperty(property_name);
      
      // TODO: Provide the virtual function
      //
      // virtual bool WillReplaceProperty(property_name, previous_value, property_value);
      //
      // that derived classes can implement for property validation
      // and custom access control (e.g. to enforce security
      // policies)."
    }
    
    bool property_set = false;
    try {
      js_object__.SetProperty(property_name, property_value, attributes);
      property_set = true;
    } catch (...) {
    }
    
    HAL_LOG_DEBUG("JSExportObject::SetProperty: property_set = ", std::to_string(property_set), " for ", property_name, " = ", to_string(property_value));
    
    // TODO: Provide the virtual function
    //
    // virtual bool DidSetProperty(property_name, previous_value, property_value);
    //
    // that derived classes can implement for their own implementation
    // concerns.
    
    return property_set;
  }
  
  bool JSExportObject::SetProperty3(unsigned property_index, const JSValue& property_value) HAL_NOEXCEPT {
    HAL_JSEXPORTOBJECT_LOCK_GUARD;
    
    // TODO: Provide the virtual function
    //
    // virtual bool WillSetProperty(property_name, property_value);
    //
    // that derived classes can implement for property validation and
    // custom access control (e.g. to enforce security policies)."
    
    JSValue previous_value = js_object__.GetProperty(property_index);
    if (!previous_value.IsUndefined()) {
      // TODO: Provide the virtual function
      //
      // virtual bool WillReplaceProperty(property_index, previous_value, property_value);
      //
      // that derived classes can implement for property validation
      // and custom access control (e.g. to enforce security
      // policies)."
    }
    
    bool property_set = false;
    try {
      js_object__.SetProperty(property_index, property_value);
      property_set = true;
    } catch (...) {
    }
    
    HAL_LOG_DEBUG("JSExportObject::SetProperty: property_set = ", std::to_string(property_set), " for ", std::to_string(property_index), " = ", to_string(property_value));
    
    // TODO: Provide the virtual function
    //
    // virtual bool DidSetProperty(property_index, previous_value, property_value);
    //
    // that derived classes can implement for their own implementation
    // concerns.
    
    return property_set;
  }

* JSClass.hpp

  /*!
    @method
    
    @abstract Return the JSClass with the given name.

    @param The name of the JSClass to return.
    
    @result The JSClass with the given name.
    
    @throws std::invalid_argument if a JSClass with the given name
    does not exist.
  */
  static JSClass GetClassWithName(const JSString& class_name);

  /*!
    @method
    
    @abstract Return the number of JSClasses created.

    @result The number of JSClasses created.
  */
  static std::size_t GetClassCount();

  /*!
    @method
    
    @abstract Return the names of the JSClasses created.

    @result The names of the JSClasses created.
  */
  static std::vector<std::string> GetClassNames();

* JSClass.cpp

JSClass JSClass::GetClassWithName(const JSString& class_name) {
	// TODO
}

std::size_t JSClass::GetClassCount() {
	// TODO
}

std::vector<std::string> JSClass::GetClassNames() {
	// TODO
}

* JSExport
** AddCallAsConstructorCallback
    /*!
     @method
     
     @abstract Set the callback to invoke when your JavaScript object
     is used as a constructor in a 'new' expression. If you provide
     this callback then you must also provide the HasInstanceCallback
     as well.
     
     @discussion If this callback doest not exist, then using your
     JavaScript object as a constructor in a 'new' expression will
     throw a JavaScript exception.
     
     For example, given this class definition:
     
     class Foo {
     JSObject Constructor(const std::vector<JSValue>& arguments);
     };
     
     You would call AddCallAsConstructorCallback like this:
     
     AddCallAsConstructorCallback(&Foo::Constructor);
     
     If your callback were invoked by the JavaScript expression 'new
     myConstructor()', then 'myConstructor' is the instance of Foo
     being called.
     
     @param call_as_constructor_callback The callback to invoke when
     your JavaScript object is used as a constructor in a 'new'
     expression. If you provide this callback then you must also
     provide the HasInstanceCallback as well.
     
     @result Your callback should return a JSObject that is the result
     of calling your JavaScript object in a 'new' expression.
     */
    static void AddCallAsConstructorCallback(const CallAsConstructorCallback<T>& call_as_constructor_callback);

** AddHasInstanceCallback    
    /*!
     @method
     
     @abstract Set the callback to invoke when your JavaScript object
     is used as the target of an 'instanceof' expression. If you
     provide this callback then you must also provide the
     CallAsConstructorCallback as well.
     
     @discussion If this callback does not exist, then 'instanceof'
     expressions that target your JavaScript object will return false.
     
     For example, given this class definition:
     
     class Foo {
     bool HasInstance(const JSValue& possible_instance) const;
     };
     
     You would call AddHasInstanceCallback like this:
     
     AddHasInstanceCallback(&Foo::HasInstance);
     
     If your callback were invoked by the JavaScript expression
     'someValue instanceof myObject', then 'myObject' is the instance
     of Foo being called and 'someValue' is the possible_instance
     parameter.
     
     @param has_instance_callback The callback to invoke when your
     JavaScript object is used as the target of an 'instanceof'
     expression. If you provide this callback then you must also
     provide the CallAsConstructorCallback as well.
     
     @result Your callback should return true to indicate whether it
     is 'instanceof' the given JSValue 'possible_instance'.
     */
    static void AddHasInstanceCallback(const HasInstanceCallback<T>& has_instance_callback);

* JSExportCallbacks
** InitializeCallback
/*! 
  @typedef InitializeCallback

  @abstract The callback to invoke when a JavaScript object is first
  created. Unlike the other object callbacks, the initialize callback
  is called on the least derived object (the parent object) first, and
  the most derived object last, analogous to the way C++ constructors
  work in a class hierarchy.
  
  For example, given this class definition:
  
  class Foo {
    void Initialize();
  };

  You would define the callback like this:
  
  InitializeCallback callback(&Foo::Initialize);
  
  @param 1 A non-const reference to the C++ object being initialized.
*/
template<typename T>
using InitializeCallback = std::function<void(T&)>;
	
** FinalizeCallback
/*! 
  @typedef FinalizeCallback

  @abstract The callback to invoke when a JavaScript object is
  finalized (prepared for garbage collection). This callback is
  invoked immediately before your C++ class destructor. An object may
  be finalized on any thread.
  
  @discussion The finalize callback is called on the most derived
  object first, and the least derived object (the parent object) last,
  analogous to that way C++ destructors work in a class hierarchy.
	  
  You must not call any function that may cause a garbage collection
  or an allocation of a garbage collected object from within a
  FinalizeCallback. This basically means don't create any object whose
  class name begins with JS (e.g. JSString, JSValue, JSObject, etc.)
  and don't call any methods on such objects that you may already have
  a reference to.
	  
  For example, given this class definition:

  class Foo {
    void Finalize(void* native_object_ptr);
  };

  You would define the callback like this:

  FinalizeCallback callback(&Foo::Finalize);

  @param 1 A non-const reference to the C++ object being finalized.

  @param 2 A pointer to the native object being finalized.
*/
template<typename T>
using FinalizeCallback = std::function<void(T&, void*)>;

** CallAsConstructorCallback
  /*!
   @typedef CallAsConstructorCallback
   
   @abstract The callback to invoke when your JavaScript object is
   used as a constructor in a 'new' expression.
   
   @discussion If this callback doest not exist, then using your
   JavaScript object as a constructor in a 'new' expression will throw
   a JavaScript exception.
   
   For example, given this class definition:
   
   class Foo {
   JSObject CallAsConstructor(const std::vector<JSValue>& arguments);
   };
   
   You would define the callback like this:
   
   CallAsConstructorCallback callback(&Foo::CallAsConstructor);
   
   If your callback were invoked by the JavaScript expression 'new
   myConstructor()', then 'myConstructor' is the instance of Foo being
   called.
   
   @param 1 A non-const reference to the C++ object that implements
   your JavaScript object.
   
   @param 2 A const rvalue reference to the JSValue array of arguments
   to pass to the constructor.
   
   @result Return a JSObject that is the result of calling your
   JavaScript object in a 'new' expression.
   */
  template<typename T>
  using CallAsConstructorCallback = std::function<JSObject(T&, const std::vector<JSValue>&)>;

** HasInstanceCallback
  /*!
   @typedef HasInstanceCallback
   
   @abstract The callback to invoke when your JavaScript object is
   used as the target of an 'instanceof' expression. If you provide
   this callback then you must also provide the
   CallAsConstructorCallback as well.
   
   @discussion If this callback does not exist, then 'instanceof'
   expressions that target your JavaScript object will return false.
   
   For example, given this class definition:
   
   class Foo {
   bool HasInstance(const JSValue& possible_instance) const;
   };
   
   You would define the callback like this:
   
   HasInstanceCallback callback(&Foo::HasInstance);
   
   If your callback were invoked by the JavaScript expression
   'someValue instanceof myObject', then 'myObject' is the instance of
   Foo being called and 'someValue' is the possible_instance
   parameter.
   
   @param 1 A const reference to the C++ object that implements your
   JavaScript object.
   
   @param 2 A const rvalue reference to the JSValue being tested to
   determine if it is an instance of parameter 1.
   
   @result Return true to indicate parameter 2 is an 'instanceof'
   parameter 1.
   */
  template<typename T>
  using HasInstanceCallback = std::function<bool(const T&, const JSValue&)>;

* JSExportClassDefinitionBuilder.hpp
** InitializeCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when a JavaScript object
	  is first created.
	  
	  @result The callback to invoke when a JavaScript object is first
	  created.
	*/
	InitializeCallback<T> Initialize() const {
		return initialize_callback__;
	}

	/*!
	  @method

	  @abstract Set the callback to invoke when a JavaScript object is
	  first created. Unlike the other object callbacks, the initialize
	  callback is called on the least derived object (the parent object)
	  first, and the most derived object last, analogous to the way C++
	  constructors work in a class hierarchy.

	  @discussion For example, given this class definition:

	  class Foo {
	    void Initialize();
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.Initialize(&Foo::Initialize);
  
	  @result A reference to the builder for chaining.
	*/
	JSClassBuilder<T>& Initialize(const InitializeCallback<T>& initialize_callback) {
		HAL_DETAIL_JSCLASSBUILDER_LOCK_GUARD;
		initialize_callback__ = initialize_callback;
		return *this;
	}

** FinalizeCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when a JavaScript object
	  is finalized (prepared for garbage collection).
  	  
	  @result The callback to invoke when a JavaScript object is
	  finalized (prepared for garbage collection).
	*/
	FinalizeCallback<T> Finalize() const {
		return finalize_callback__;
	}

	/*!
	  @method

	  @abstract Set the callback to invoke when a JavaScript object is
	  finalized (prepared for garbage collection). This callback is
	  invoked immediately before your C++ class destructor. An object
	  may be finalized on any thread.

	  @discussion The finalize callback is called on the most derived
	  object first, and the least derived object (the parent object)
	  last, analogous to that way C++ destructors work in a class
	  hierarchy.
	  
	  You must not call any function that may cause a garbage collection
	  or an allocation of a garbage collected object from within a
	  FinalizeCallback. This basically means don't create any object
	  whose class name begins with JS (e.g. JSString, JSValue, JSObject,
	  etc.)  and don't call any methods on such objects that you may
	  already have a reference to.
	  
	  For example, given this class definition:

	  class Foo {
	    void Finalize();
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.Finalize(&Foo::Finalize);

	  @result A reference to the builder for chaining.
	*/
	JSClassBuilder<T>& Finalize(const FinalizeCallback<T>& finalize_callback) {
		HAL_DETAIL_JSCLASSBUILDER_LOCK_GUARD;
		finalize_callback__ = finalize_callback;
		return *this;
	}

** HasPropertyCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when determining whether a
	  JavaScript object has a property.
  
	  @result The callback to invoke when determining whether a
	  JavaScript object has a property.

	HasPropertyCallback<T> HasProperty() const {
		return has_property_callback_;
	}
	*/

	/*!
	  @method

	  @abstract Set the callback to invoke when determining whether a
	  JavaScript object has a property. If this callback is missing then
	  the object will delegate to the GetPropertyCallback.
  
	  @discussion The HasPropertyCallback enables optimization in cases
	  where only a property's existence needs to be known, not its
	  value, and computing its value is expensive. If the
	  HasPropertyCallback doesn't exist, then the GetPropertyCallback
	  will be used instead.

	  If this function returns false then the reqeust forwards to
	  properties added by the AddValuePropertyCallback method (if any),
	  then properties vended by the class' parent class chain, then
	  properties belonging to the JavaScript object's prototype chain.

	  For example, given this class definition:

	  class Foo {
	    bool HasProperty(const JSString& property_name) const;
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.HasProperty(&Foo::HasProperty);

	  @result A reference to the builder for chaining.

	JSClassBuilder<T>& HasProperty(const HasPropertyCallback<T>& has_property_callback) {
		has_property_callback_ = has_property_callback;
		return *this;
	}
	*/

** GetPropertyCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when getting a property's
	  value from a JavaScript object.
  	  
	  @result The callback to invoke when getting a property's value
	  from a JavaScript object.

	GetPropertyCallback<T> GetProperty() const {
		return get_property_callback_;
	}
	*/

	/*!
	  @method

	  @abstract Set the callback to invoke when getting a property's
	  value from a JavaScript object.
	  
	  @discussion If this function returns JSUndefined, the get request
	  forwards to properties added by the AddValuePropertyCallback
	  method (if any), properties vended by the class' parent class
	  chain, then properties belonging to the JavaScript object's
	  prototype chain.

	  For example, given this class definition:

	  class Foo {
	    JSValue GetProperty(const JSString& property_name) const;
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.GetProperty(&Foo::GetProperty);
	  
	  @result A reference to the builder for chaining.

	JSClassBuilder<T>& GetProperty(const GetPropertyCallback<T>& get_property_callback) {
		get_property_callback_ = get_property_callback;
		return *this;
	}
	*/

** SetPropertyCallback	
	/*!
	  @method

	  @abstract Return the callback to invoke when setting a property's
	  value on a JavaScript object.
  	  
	  @result The callback to invoke when setting a property's value on
	  a JavaScript object.

	SetPropertyCallback<T> SetProperty() const {
		return set_property_callback_;
	}
	*/

	/*!
	  @method

	  @abstract Set the callback to invoke when setting a property's
	  value on a JavaScript object.

	  @discussion If this callback returns false then the request
	  forwards to properties added by the AddValuePropertyCallback
	  method (if any), then properties vended by the class' parent class
	  chain, then properties belonging to the JavaScript object's
	  prototype chain.

	  For example, given this class definition:

	  class Foo {
	    bool SetProperty(const JSString& property_name, const JSValue& value);
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.SetProperty(&Foo::SetProperty);
  
	  @result A reference to the builder for chaining.

	JSClassBuilder<T>& SetProperty(const SetPropertyCallback<T>& set_property_callback) {
		set_property_callback_ = set_property_callback;
		return *this;
	}
	*/

** DeletePropertyCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when deleting a property
	  from a JavaScript object.
  	  
	  @result The callback to invoke when deleting a property from a
	  JavaScript object.

	DeletePropertyCallback<T> DeleteProperty() const {
		return delete_property_callback_;
	}
	*/

	/*!
	  @method

	  @abstract Set the callback to invoke when deleting a property from
	  a JavaScript object.
  	  
	  @discussion If this function returns false then the request
	  forwards to properties added by the AddValuePropertyCallback
	  method (if any), then properties vended by the class' parent class
	  chain, then properties belonging to the JavaScript object's
	  prototype chain.

	  For example, given this class definition:

	  class Foo {
	    bool DeleteProperty(const JSString& property_name);
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.DeleteProperty(&Foo::DeleteProperty);

	  @result A reference to the builder for chaining.

	JSClassBuilder<T>& DeleteProperty(const DeletePropertyCallback<T>& delete_property_callback) {
		delete_property_callback_ = delete_property_callback;
		return *this;
	}
	*/

** GetPropertyNamesCallback
	/*!
	  @method

	  @abstract Return the callback to invoke when collecting the names
	  of a JavaScript object's properties.
  	  
	  @result The callback to invoke when collecting the names of a
	  JavaScript object's properties

	GetPropertyNamesCallback<T> GetPropertyNames() const {
		return get_property_names_callback_;
	}
	*/

	/*!
	  @method

	  @abstract Set the callback to invoke when collecting the names of
	  a JavaScript object's properties.
	  
	  @discussion The GetPropertyNamesCallback only needs to provide the
	  property names provided by the GetPropertyCallback and/or
	  SetPropertyCallback callbacks (if any). Other property names are
	  automatically added from properties provided by the
	  AddValuePropertyCallback method (if any), then properties vended
	  by the class' parent class chain, then properties belonging to the
	  JavaScript object's prototype chain.
	  
	  For example, given this class definition:

	  class Foo {
	    void GetPropertyNames(const JSPropertyNameAccumulator& accumulator) const;
	  };

	  You would call the builer like this:

	  JSClassBuilder<Foo> builder("Foo");
	  builder.GetPropertyNames(&Foo::GetPropertyNames);
	  
	  Property name accumulators are used by JavaScript for...in loops.
	  Use JSPropertyNameAccumulator::AddName to add property names to
	  accumulator.

	  @result A reference to the builder for chaining.

	JSClassBuilder<T>& GetPropertyNames(const GetPropertyNamesCallback<T>& get_property_names_callback) {
		get_property_names_callback_ = get_property_names_callback;
		return *this;
	}
	*/

** CallAsFunctionCallback
    /*!
     @method
     
     @abstract Return the callback to invoke when a JavaScript object
     is called as a function.
     
     @result The callback to invoke when a JavaScript object is called
     as a function.
     */
    CallAsFunctionCallback<T> Function() const noexcept {
      return call_as_function_callback__;
    }
    
    /*!
     @method
     
     @abstract Set the callback to invoke when a JavaScript object is
     called as a function.
     
     @discussion If this callback does not exist, then calling your
     object as a function will throw a JavaScript exception.
     
     For example, given this class definition:
     
     class Foo {
     JSValue DoSomething(std::vector<JSValue>&& arguments, JSObject&& this_object);
     };
     
     You would call the builer like this:
     
     JSExportClassDefinitionBuilder<Foo> builder("Foo");
     builder.Function(&Foo::DoSomething);
     
     In the JavaScript expression 'myObject.myFunction()', then
     'myFunction' is the instance of Foo being called, and this_object
     would be set to 'myObject'.
     
     In the JavaScript expression 'myFunction()', then both
     'myFunction' and 'myObject' is the instance of Foo being called.
     
     @result A reference to the builder for chaining.
     */
    JSExportClassDefinitionBuilder<T>& Function(const CallAsFunctionCallback<T>& call_as_function_callback) noexcept {
      HAL_DETAIL_JSEXPORTCLASSDEFINITIONBUILDER_LOCK_GUARD;
      call_as_function_callback__ = call_as_function_callback;
      return *this;
    }

** CallAsConstructorCallback
    /*!
     @method
     
     @abstract Return the callback to invoke when your JavaScript
     object is used as a constructor in a 'new' expression. If you
     provide this callback then you must also provide the
     HasInstanceCallback as well.
     
     @result The callback to invoke when your JavaScript object is
     used as a constructor in a 'new' expression.
     */
    CallAsConstructorCallback<T> Constructor() const HAL_NOEXCEPT {
      return call_as_constructor_callback__;
    }
    
    /*!
     @method
     
     @abstract Set the callback to invoke when your JavaScript object
     is used as a constructor in a 'new' expression. If you provide
     this callback then you must also provide the HasInstanceCallback
     as well.
     
     @discussion If this callback doest not exist, then using your
     JavaScript object as a constructor in a 'new' expression will
     throw a JavaScript exception.
     
     For example, given this class definition:
     
     class Foo {
     JSObject Constructor(const std::vector<JSValue>& arguments);
     };
     
     You would call the builer like this:
     
     JSClassBuilder<Foo> builder("Foo");
     builder.Constructor(&Foo::Constructor);
     
     If your callback were invoked by the JavaScript expression
     'new myConstructor()', then 'myConstructor' is the instance of
     Foo being called.
     
     @result A reference to the builder for chaining.
     */
    JSExportClassDefinitionBuilder<T>& Constructor(const CallAsConstructorCallback<T>& call_as_constructor_callback) HAL_NOEXCEPT {
      HAL_DETAIL_JSEXPORTCLASSDEFINITIONBUILDER_LOCK_GUARD;
      call_as_constructor_callback__ = call_as_constructor_callback;
      return *this;
    }

** HasInstanceCallback	
    /*!
     @method
     
     @abstract Return the callback to invoke when your JavaScript
     object is used as the target of an 'instanceof' expression. If
     you provide this callback then you must also provide the
     CallAsConstructorCallback as well.
     
     @result The callback to invoke when your JavaScript object is
     used as the target of an 'instanceof' expression.
     */
    HasInstanceCallback<T> HasInstance() const HAL_NOEXCEPT {
      return has_instance_callback__;
    }
    
    /*!
     @method
     
     @abstract Set the callback to invoke when your JavaScript object
     is used as the target of an 'instanceof' expression. If you
     provide this callback then you must also provide the
     CallAsConstructorCallback as well.
     
     @discussion If this callback does not exist, then 'instanceof'
     expressions that target your JavaScript object will return false.
     
     For example, given this class definition:
     
     class Foo {
     bool HasInstance(const JSValue& possible_instance) const;
     };
     
     You would call the builer like this:
     
     JSClassBuilder<Foo> builder("Foo");
     builder.HasInstance(&Foo::HasInstance);
     
     If your callback were invoked by the JavaScript expression
     'someValue instanceof myObject', then 'myObject' is the instance
     of Foo being called and 'someValue' is the possible_instance
     parameter.
     
     @result A reference to the builder for chaining.
     */
    JSExportClassDefinitionBuilder<T>& HasInstance(const HasInstanceCallback<T>& has_instance_callback) HAL_NOEXCEPT {
      HAL_DETAIL_JSEXPORTCLASSDEFINITIONBUILDER_LOCK_GUARD;
      has_instance_callback__ = has_instance_callback;
      return *this;
    }
    
** ConvertToTypeCallback
    /*!
     @method
     
     @abstract Return the callback to invoke when converting a
     JavaScript object another JavaScript type.
     
     @result The callback to invoke when converting a JavaScript object
     to another JavaScript type.
     */
     ConvertToTypeCallback<T> ConvertToType() const noexcept {
       return convert_to_type_callback__;
     }
    
    /*!
     @method
     
     @abstract Set the callback to invoke when converting a JavaScript
     object to another JavaScript type. This function is only invoked
     when converting an object to a number or a string. An object
     converted to boolean is 'true.' An object converted to object is
     itself.
     
     @discussion If this function returns JSUndefined, then the
     conversion request forwards the reqeust to the JSClass' parent
     class chain, then the JavaScript object's prototype chain.
     
     For example, given this class definition:
     
     class Foo {
     JSValue ConvertToType(JSValue::Type&& type) const;
     };
     
     You would call the builer like this:
     
     JSExportClassDefinitionBuilder<Foo> builder("Foo");
     builder.ConvertToType(&Foo::ConvertToType);
     
     @result A reference to the builder for chaining.
     */
     JSExportClassDefinitionBuilder<T>& ConvertToType(const ConvertToTypeCallback<T>& convert_to_type_callback) noexcept {
       HAL_DETAIL_JSEXPORTCLASSDEFINITIONBUILDER_LOCK_GUARD;
       convert_to_type_callback__ = convert_to_type_callback;
       return *this;
     }

** RemoveAllValueProperties
	/*!
	  @method

	  @abstract Remove all callbacks added by the AddValueProperty
	  method.
	  
	  @result A reference to the builder for chaining.
	JSClassBuilder<T>& RemoveAllValueProperties() {
		value_property_callback_map_.clear();
		return *this;
	}
	*/

** RemoveAllFunctionProperties
	/*!
	  @method

	  @abstract Remove all callbacks added by the AddFunctionProperty
	  method.
	  
	  @result A reference to the builder for chaining.
	JSClassBuilder<T>& RemoveAllFunctionProperties() {
		function_property_callback_map_.clear();
		return *this;
	}
	*/
* HAL
** RAII
commit 7f637082057e94e077b10e1ef78c9cf2a133b088
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Mon Nov 3 20:43:29 2014 -0800
** RAII2
commit 6ff6399c1bb946f223a99fb522fd1d5155a32cbc
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Thu Nov 6 06:11:45 2014 -0800
** RAII3
commit f7e0286df981ecb4a3d31616866d1c49deff6270
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Thu Nov 6 18:10:49 2014 -0800
** RAII4
commit d9c45c9bf19e53ee7eae1cf4847dcded182f030c
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Sat Nov 8 22:52:39 2014 -0800
** RAII5
commit 51aec088df330c1097714903ddd225a292f3410d
Author: Matt Langston <matt_langston@mac.com>
Date:   Mon Nov 10 02:57:04 2014 +0000
** RAII6
commit c551e4bcc92602ab9b844b304d225b92a9a504d6
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Sun Nov 9 22:05:02 2014 -0800
** RAII
After merging RAII2, RAII3, RAII4, RAII5 and RAII6 into RAII
commit c551e4bcc92602ab9b844b304d225b92a9a504d6
Author: matt-langston <matt-langston@users.noreply.github.com>
Date:   Sun Nov 9 22:05:02 2014 -0800
